drivers=sgp30 sgpc3
clean_drivers=$(foreach d, $(drivers), clean_$(d))
release_drivers=$(foreach d, $(drivers), release/$(d))

.PHONY: FORCE all $(release_drivers) $(clean_drivers)

all: $(drivers)

$(drivers): sgp-common/git_version.c FORCE
	cd $@ && $(MAKE) $(MFLAGS)

sgp-common/git_version.c: FORCE
	[ -d ".git" ] && git describe --always --dirty | \
		awk 'BEGIN \
		{print "/* THIS FILE IS AUTOGENERATED */"} \
		{print "#include \"git_version.h\""} \
		{print "const char * SGP_DRV_VERSION_STR = \"" $$0"\";"} \
		END {}' > $@ || echo "Can't update version, not a git repository"

svm30: FORCE
	cd $@ && $(MAKE) $(MFLAGS)

$(release_drivers): sgp-common/git_version.c
	export rel=$@ && \
	export driver=$${rel#release/} && \
	export tag="$$(git describe --always --dirty)" && \
	export pkgname="$${driver}-$${tag}" && \
	export pkgdir="release/$${pkgname}" && \
	rm -rf "$${pkgdir}" && mkdir -p "$${pkgdir}" && \
	cp -r embedded-common/* "$${pkgdir}" && \
	cp -r sgp-common/* "$${pkgdir}" && \
	cp -r $${driver}/* "$${pkgdir}" && \
	perl -pi -e 's/^sensirion_common_dir :=.*$$/sensirion_common_dir := ./' "$${pkgdir}/Makefile" && \
	perl -pi -e 's/^sgp_common_dir :=.*$$/sgp_common_dir := ./' "$${pkgdir}/Makefile" && \
	cd "$${pkgdir}" && $(MAKE) $(MFLAGS) && $(MAKE) clean $(MFLAGS) && cd - && \
	cd release && zip -r "$${pkgname}.zip" "$${pkgname}" && cd - && \
	ln -sf $${pkgname} $@

release/sgpc3-shtc1-combo-driver: release/sgpc3
	export rel=$@ && \
	export sht_driver=../embedded-sht/release/shtc1 && \
	export sgp_driver=./release/sgpc3 && \
	export driver=svm30 && \
	export tag="$$(git describe --always --dirty)" && \
	export pkgname="sgpc3-shtc1-combo-driver-$${tag}" && \
	export pkgdir="release/$${pkgname}" && \
	rm -rf "$${pkgdir}" && mkdir -p "$${pkgdir}" && \
	cp -r $${sht_driver}/* "$${pkgdir}" && \
	cp -r $${sgp_driver}/* "$${pkgdir}" && \
	grep SHT_DRV_VERSION_STR $${sht_driver}/git_version.h >> $${pkgdir}/git_version.h && \
	grep SHT_DRV_VERSION_STR $${sht_driver}/git_version.c >> $${pkgdir}/git_version.c && \
	cp -r $${driver}/* "$${pkgdir}" && \
	perl -pi -e 's/^sensirion_common_dir :=.*$$/sensirion_common_dir := ./' "$${pkgdir}/Makefile" && \
	perl -pi -e 's/^sgp_common_dir :=.*$$/sgp_common_dir := ./' "$${pkgdir}/Makefile" && \
	perl -pi -e 's/^sgp_source_dir :=.*$$/sgp_source_dir := ./' "$${pkgdir}/Makefile" && \
	perl -pi -e 's/^sht_common_dir :=.*$$/sht_common_dir := ./' "$${pkgdir}/Makefile" && \
	perl -pi -e 's/^sht_source_dir :=.*$$/sht_source_dir := ./' "$${pkgdir}/Makefile" && \
	cd "$${pkgdir}" && $(MAKE) $(MFLAGS) && $(MAKE) clean $(MFLAGS) && cd - && \
	cd release && zip -r "$${pkgname}.zip" "$${pkgname}" && cd - && \
	ln -sf $${pkgname} $@

release: clean $(release_drivers)

$(clean_drivers):
	export rel=$@ && \
	export driver=$${rel#clean_} && \
	cd $${driver} && $(MAKE) clean $(MFLAGS) && cd -

clean: $(clean_drivers)
	cd svm30 && $(MAKE) clean $(MFLAGS) && cd - && \
	rm -rf release
